// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: gophkeeper.proto

package gophkeeper_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GophkeeperService_CreateUser_FullMethodName        = "/paulwwyvern.gophkeeper_proto.GophkeeperService/CreateUser"
	GophkeeperService_Login_FullMethodName             = "/paulwwyvern.gophkeeper_proto.GophkeeperService/Login"
	GophkeeperService_GetUser_FullMethodName           = "/paulwwyvern.gophkeeper_proto.GophkeeperService/GetUser"
	GophkeeperService_PushChanges_FullMethodName       = "/paulwwyvern.gophkeeper_proto.GophkeeperService/PushChanges"
	GophkeeperService_PullChanges_FullMethodName       = "/paulwwyvern.gophkeeper_proto.GophkeeperService/PullChanges"
	GophkeeperService_UploadFileQuery_FullMethodName   = "/paulwwyvern.gophkeeper_proto.GophkeeperService/UploadFileQuery"
	GophkeeperService_UploadFileStatus_FullMethodName  = "/paulwwyvern.gophkeeper_proto.GophkeeperService/UploadFileStatus"
	GophkeeperService_UploadFile_FullMethodName        = "/paulwwyvern.gophkeeper_proto.GophkeeperService/UploadFile"
	GophkeeperService_DownloadFileQuery_FullMethodName = "/paulwwyvern.gophkeeper_proto.GophkeeperService/DownloadFileQuery"
	GophkeeperService_DownloadFile_FullMethodName      = "/paulwwyvern.gophkeeper_proto.GophkeeperService/DownloadFile"
)

// GophkeeperServiceClient is the client API for GophkeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophkeeperServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// методы защищённые auth middleware
	GetUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*User, error)
	PushChanges(ctx context.Context, in *PushChangesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PullChanges(ctx context.Context, in *PullChangesRequest, opts ...grpc.CallOption) (*PullChangesResponse, error)
	UploadFileQuery(ctx context.Context, in *UploadFileQueryRequest, opts ...grpc.CallOption) (*UploadFileQueryResponse, error)
	UploadFileStatus(ctx context.Context, in *UploadFileStatusRequest, opts ...grpc.CallOption) (*UploadFileStatusResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileChunk, UploadFileResponse], error)
	DownloadFileQuery(ctx context.Context, in *DownloadFileQueryRequest, opts ...grpc.CallOption) (*DownloadFileQueryResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileChunk], error)
}

type gophkeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGophkeeperServiceClient(cc grpc.ClientConnInterface) GophkeeperServiceClient {
	return &gophkeeperServiceClient{cc}
}

func (c *gophkeeperServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, GophkeeperService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, GophkeeperService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) GetUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GophkeeperService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) PushChanges(ctx context.Context, in *PushChangesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GophkeeperService_PushChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) PullChanges(ctx context.Context, in *PullChangesRequest, opts ...grpc.CallOption) (*PullChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullChangesResponse)
	err := c.cc.Invoke(ctx, GophkeeperService_PullChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) UploadFileQuery(ctx context.Context, in *UploadFileQueryRequest, opts ...grpc.CallOption) (*UploadFileQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileQueryResponse)
	err := c.cc.Invoke(ctx, GophkeeperService_UploadFileQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) UploadFileStatus(ctx context.Context, in *UploadFileStatusRequest, opts ...grpc.CallOption) (*UploadFileStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileStatusResponse)
	err := c.cc.Invoke(ctx, GophkeeperService_UploadFileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileChunk, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophkeeperService_ServiceDesc.Streams[0], GophkeeperService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileChunk, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophkeeperService_UploadFileClient = grpc.ClientStreamingClient[UploadFileChunk, UploadFileResponse]

func (c *gophkeeperServiceClient) DownloadFileQuery(ctx context.Context, in *DownloadFileQueryRequest, opts ...grpc.CallOption) (*DownloadFileQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadFileQueryResponse)
	err := c.cc.Invoke(ctx, GophkeeperService_DownloadFileQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophkeeperService_ServiceDesc.Streams[1], GophkeeperService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, DownloadFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophkeeperService_DownloadFileClient = grpc.ServerStreamingClient[DownloadFileChunk]

// GophkeeperServiceServer is the server API for GophkeeperService service.
// All implementations must embed UnimplementedGophkeeperServiceServer
// for forward compatibility.
type GophkeeperServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// методы защищённые auth middleware
	GetUser(context.Context, *emptypb.Empty) (*User, error)
	PushChanges(context.Context, *PushChangesRequest) (*emptypb.Empty, error)
	PullChanges(context.Context, *PullChangesRequest) (*PullChangesResponse, error)
	UploadFileQuery(context.Context, *UploadFileQueryRequest) (*UploadFileQueryResponse, error)
	UploadFileStatus(context.Context, *UploadFileStatusRequest) (*UploadFileStatusResponse, error)
	UploadFile(grpc.ClientStreamingServer[UploadFileChunk, UploadFileResponse]) error
	DownloadFileQuery(context.Context, *DownloadFileQueryRequest) (*DownloadFileQueryResponse, error)
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[DownloadFileChunk]) error
	mustEmbedUnimplementedGophkeeperServiceServer()
}

// UnimplementedGophkeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGophkeeperServiceServer struct{}

func (UnimplementedGophkeeperServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedGophkeeperServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGophkeeperServiceServer) GetUser(context.Context, *emptypb.Empty) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedGophkeeperServiceServer) PushChanges(context.Context, *PushChangesRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PushChanges not implemented")
}
func (UnimplementedGophkeeperServiceServer) PullChanges(context.Context, *PullChangesRequest) (*PullChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullChanges not implemented")
}
func (UnimplementedGophkeeperServiceServer) UploadFileQuery(context.Context, *UploadFileQueryRequest) (*UploadFileQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFileQuery not implemented")
}
func (UnimplementedGophkeeperServiceServer) UploadFileStatus(context.Context, *UploadFileStatusRequest) (*UploadFileStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFileStatus not implemented")
}
func (UnimplementedGophkeeperServiceServer) UploadFile(grpc.ClientStreamingServer[UploadFileChunk, UploadFileResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedGophkeeperServiceServer) DownloadFileQuery(context.Context, *DownloadFileQueryRequest) (*DownloadFileQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadFileQuery not implemented")
}
func (UnimplementedGophkeeperServiceServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[DownloadFileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedGophkeeperServiceServer) mustEmbedUnimplementedGophkeeperServiceServer() {}
func (UnimplementedGophkeeperServiceServer) testEmbeddedByValue()                           {}

// UnsafeGophkeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophkeeperServiceServer will
// result in compilation errors.
type UnsafeGophkeeperServiceServer interface {
	mustEmbedUnimplementedGophkeeperServiceServer()
}

func RegisterGophkeeperServiceServer(s grpc.ServiceRegistrar, srv GophkeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedGophkeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GophkeeperService_ServiceDesc, srv)
}

func _GophkeeperService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).GetUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_PushChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).PushChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_PushChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).PushChanges(ctx, req.(*PushChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_PullChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).PullChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_PullChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).PullChanges(ctx, req.(*PullChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_UploadFileQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).UploadFileQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_UploadFileQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).UploadFileQuery(ctx, req.(*UploadFileQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_UploadFileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).UploadFileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_UploadFileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).UploadFileStatus(ctx, req.(*UploadFileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GophkeeperServiceServer).UploadFile(&grpc.GenericServerStream[UploadFileChunk, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophkeeperService_UploadFileServer = grpc.ClientStreamingServer[UploadFileChunk, UploadFileResponse]

func _GophkeeperService_DownloadFileQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServiceServer).DownloadFileQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophkeeperService_DownloadFileQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServiceServer).DownloadFileQuery(ctx, req.(*DownloadFileQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophkeeperService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GophkeeperServiceServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, DownloadFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophkeeperService_DownloadFileServer = grpc.ServerStreamingServer[DownloadFileChunk]

// GophkeeperService_ServiceDesc is the grpc.ServiceDesc for GophkeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GophkeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paulwwyvern.gophkeeper_proto.GophkeeperService",
	HandlerType: (*GophkeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _GophkeeperService_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GophkeeperService_Login_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _GophkeeperService_GetUser_Handler,
		},
		{
			MethodName: "PushChanges",
			Handler:    _GophkeeperService_PushChanges_Handler,
		},
		{
			MethodName: "PullChanges",
			Handler:    _GophkeeperService_PullChanges_Handler,
		},
		{
			MethodName: "UploadFileQuery",
			Handler:    _GophkeeperService_UploadFileQuery_Handler,
		},
		{
			MethodName: "UploadFileStatus",
			Handler:    _GophkeeperService_UploadFileStatus_Handler,
		},
		{
			MethodName: "DownloadFileQuery",
			Handler:    _GophkeeperService_DownloadFileQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _GophkeeperService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _GophkeeperService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gophkeeper.proto",
}
