// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: gophkeeper.proto

package gophkeeper_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Salt          []byte                 `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	VaultKey      []byte                 `protobuf:"bytes,4,opt,name=vaultKey,proto3" json:"vaultKey,omitempty"`
	VaultKeyNonce []byte                 `protobuf:"bytes,5,opt,name=vaultKey_nonce,json=vaultKeyNonce,proto3" json:"vaultKey_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *User) GetVaultKey() []byte {
	if x != nil {
		return x.VaultKey
	}
	return nil
}

func (x *User) GetVaultKeyNonce() []byte {
	if x != nil {
		return x.VaultKeyNonce
	}
	return nil
}

type VaultItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label          int32                  `protobuf:"varint,2,opt,name=label,proto3" json:"label,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EncryptedNonce []byte                 `protobuf:"bytes,8,opt,name=encrypted_nonce,json=encryptedNonce,proto3" json:"encrypted_nonce,omitempty"`
	Encrypted      []byte                 `protobuf:"bytes,9,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VaultItem) Reset() {
	*x = VaultItem{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItem) ProtoMessage() {}

func (x *VaultItem) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultItem.ProtoReflect.Descriptor instead.
func (*VaultItem) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *VaultItem) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *VaultItem) GetLabel() int32 {
	if x != nil {
		return x.Label
	}
	return 0
}

func (x *VaultItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VaultItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VaultItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VaultItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VaultItem) GetEncryptedNonce() []byte {
	if x != nil {
		return x.EncryptedNonce
	}
	return nil
}

func (x *VaultItem) GetEncrypted() []byte {
	if x != nil {
		return x.Encrypted
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AuthKey       []byte                 `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	AuthKey       []byte                 `protobuf:"bytes,2,opt,name=authKey,proto3" json:"authKey,omitempty"`
	DeviceId      []byte                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *LoginRequest) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type PushChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VaultItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushChangesRequest) Reset() {
	*x = PushChangesRequest{}
	mi := &file_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushChangesRequest) ProtoMessage() {}

func (x *PushChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushChangesRequest.ProtoReflect.Descriptor instead.
func (*PushChangesRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *PushChangesRequest) GetItems() []*VaultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PullChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTime  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullChangesRequest) Reset() {
	*x = PullChangesRequest{}
	mi := &file_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChangesRequest) ProtoMessage() {}

func (x *PullChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChangesRequest.ProtoReflect.Descriptor instead.
func (*PullChangesRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *PullChangesRequest) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *PullChangesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PullChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VaultItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	SyncTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullChangesResponse) Reset() {
	*x = PullChangesResponse{}
	mi := &file_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChangesResponse) ProtoMessage() {}

func (x *PullChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChangesResponse.ProtoReflect.Descriptor instead.
func (*PullChangesResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *PullChangesResponse) GetItems() []*VaultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PullChangesResponse) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

func (x *PullChangesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type UploadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileChunk) Reset() {
	*x = UploadFileChunk{}
	mi := &file_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileChunk) ProtoMessage() {}

func (x *UploadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileChunk.ProtoReflect.Descriptor instead.
func (*UploadFileChunk) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *UploadFileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type UploadFileQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileQueryRequest) Reset() {
	*x = UploadFileQueryRequest{}
	mi := &file_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileQueryRequest) ProtoMessage() {}

func (x *UploadFileQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileQueryRequest.ProtoReflect.Descriptor instead.
func (*UploadFileQueryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileQueryRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileQueryRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadFileQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int32                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileToken     string                 `protobuf:"bytes,2,opt,name=file_token,json=fileToken,proto3" json:"file_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileQueryResponse) Reset() {
	*x = UploadFileQueryResponse{}
	mi := &file_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileQueryResponse) ProtoMessage() {}

func (x *UploadFileQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileQueryResponse.ProtoReflect.Descriptor instead.
func (*UploadFileQueryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *UploadFileQueryResponse) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *UploadFileQueryResponse) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

type UploadFileStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int32                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileStatusRequest) Reset() {
	*x = UploadFileStatusRequest{}
	mi := &file_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileStatusRequest) ProtoMessage() {}

func (x *UploadFileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileStatusRequest.ProtoReflect.Descriptor instead.
func (*UploadFileStatusRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *UploadFileStatusRequest) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type UploadFileStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesReceived int64                  `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	FileToken     string                 `protobuf:"bytes,2,opt,name=file_token,json=fileToken,proto3" json:"file_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileStatusResponse) Reset() {
	*x = UploadFileStatusResponse{}
	mi := &file_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileStatusResponse) ProtoMessage() {}

func (x *UploadFileStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileStatusResponse.ProtoReflect.Descriptor instead.
func (*UploadFileStatusResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *UploadFileStatusResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *UploadFileStatusResponse) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadFileRequest) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type DownloadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileChunk) Reset() {
	*x = DownloadFileChunk{}
	mi := &file_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileChunk) ProtoMessage() {}

func (x *DownloadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileChunk.ProtoReflect.Descriptor instead.
func (*DownloadFileChunk) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadFileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadFileChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type DownloadFileQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int32                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileQueryRequest) Reset() {
	*x = DownloadFileQueryRequest{}
	mi := &file_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileQueryRequest) ProtoMessage() {}

func (x *DownloadFileQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileQueryRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileQueryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadFileQueryRequest) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DownloadFileQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileToken     string                 `protobuf:"bytes,2,opt,name=file_token,json=fileToken,proto3" json:"file_token,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileQueryResponse) Reset() {
	*x = DownloadFileQueryResponse{}
	mi := &file_gophkeeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileQueryResponse) ProtoMessage() {}

func (x *DownloadFileQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileQueryResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileQueryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadFileQueryResponse) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

func (x *DownloadFileQueryResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\x1cpaulwwyvern.gophkeeper_proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\fR\x04salt\x12\x1a\n" +
	"\bvaultKey\x18\x04 \x01(\fR\bvaultKey\x12%\n" +
	"\x0evaultKey_nonce\x18\x05 \x01(\fR\rvaultKeyNonce\"\xa6\x02\n" +
	"\tVaultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\x05R\x05label\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0fencrypted_nonce\x18\b \x01(\fR\x0eencryptedNonce\x12\x1c\n" +
	"\tencrypted\x18\t \x01(\fR\tencrypted\"f\n" +
	"\x11CreateUserRequest\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".paulwwyvern.gophkeeper_proto.UserR\x04user\x12\x19\n" +
	"\bauth_key\x18\x02 \x01(\fR\aauthKey\"$\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"[\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x18\n" +
	"\aauthKey\x18\x02 \x01(\fR\aauthKey\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\fR\bdeviceId\"]\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x126\n" +
	"\x04user\x18\x02 \x01(\v2\".paulwwyvern.gophkeeper_proto.UserR\x04user\"S\n" +
	"\x12PushChangesRequest\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.paulwwyvern.gophkeeper_proto.VaultItemR\x05items\"n\n" +
	"\x12PullChangesRequest\x12@\n" +
	"\x0elast_sync_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xa8\x01\n" +
	"\x13PullChangesResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.paulwwyvern.gophkeeper_proto.VaultItemR\x05items\x127\n" +
	"\tsync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"V\n" +
	"\x0fUploadFileChunk\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"m\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rbytes_written\x18\x03 \x01(\x03R\fbytesWritten\"R\n" +
	"\x16UploadFileQueryRequest\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\"Q\n" +
	"\x17UploadFileQueryResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x05R\x06fileId\x12\x1d\n" +
	"\n" +
	"file_token\x18\x02 \x01(\tR\tfileToken\"2\n" +
	"\x17UploadFileStatusRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x05R\x06fileId\"`\n" +
	"\x18UploadFileStatusResponse\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x03R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"file_token\x18\x02 \x01(\tR\tfileToken\":\n" +
	"\x13DownloadFileRequest\x12#\n" +
	"\rbytes_written\x18\x03 \x01(\x03R\fbytesWritten\"X\n" +
	"\x11DownloadFileChunk\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"3\n" +
	"\x18DownloadFileQueryRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x05R\x06fileId\"W\n" +
	"\x19DownloadFileQueryResponse\x12\x1d\n" +
	"\n" +
	"file_token\x18\x02 \x01(\tR\tfileToken\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize2\xec\b\n" +
	"\x11GophkeeperService\x12o\n" +
	"\n" +
	"CreateUser\x12/.paulwwyvern.gophkeeper_proto.CreateUserRequest\x1a0.paulwwyvern.gophkeeper_proto.CreateUserResponse\x12`\n" +
	"\x05Login\x12*.paulwwyvern.gophkeeper_proto.LoginRequest\x1a+.paulwwyvern.gophkeeper_proto.LoginResponse\x12E\n" +
	"\aGetUser\x12\x16.google.protobuf.Empty\x1a\".paulwwyvern.gophkeeper_proto.User\x12W\n" +
	"\vPushChanges\x120.paulwwyvern.gophkeeper_proto.PushChangesRequest\x1a\x16.google.protobuf.Empty\x12r\n" +
	"\vPullChanges\x120.paulwwyvern.gophkeeper_proto.PullChangesRequest\x1a1.paulwwyvern.gophkeeper_proto.PullChangesResponse\x12~\n" +
	"\x0fUploadFileQuery\x124.paulwwyvern.gophkeeper_proto.UploadFileQueryRequest\x1a5.paulwwyvern.gophkeeper_proto.UploadFileQueryResponse\x12\x81\x01\n" +
	"\x10UploadFileStatus\x125.paulwwyvern.gophkeeper_proto.UploadFileStatusRequest\x1a6.paulwwyvern.gophkeeper_proto.UploadFileStatusResponse\x12o\n" +
	"\n" +
	"UploadFile\x12-.paulwwyvern.gophkeeper_proto.UploadFileChunk\x1a0.paulwwyvern.gophkeeper_proto.UploadFileResponse(\x01\x12\x84\x01\n" +
	"\x11DownloadFileQuery\x126.paulwwyvern.gophkeeper_proto.DownloadFileQueryRequest\x1a7.paulwwyvern.gophkeeper_proto.DownloadFileQueryResponse\x12t\n" +
	"\fDownloadFile\x121.paulwwyvern.gophkeeper_proto.DownloadFileRequest\x1a/.paulwwyvern.gophkeeper_proto.DownloadFileChunk0\x01B*Z(github.com/paulwwyvern/gophkeeper-proto/b\x06proto3"

var (
	file_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_proto_rawDescData
}

var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_gophkeeper_proto_goTypes = []any{
	(*User)(nil),                      // 0: paulwwyvern.gophkeeper_proto.User
	(*VaultItem)(nil),                 // 1: paulwwyvern.gophkeeper_proto.VaultItem
	(*CreateUserRequest)(nil),         // 2: paulwwyvern.gophkeeper_proto.CreateUserRequest
	(*CreateUserResponse)(nil),        // 3: paulwwyvern.gophkeeper_proto.CreateUserResponse
	(*LoginRequest)(nil),              // 4: paulwwyvern.gophkeeper_proto.LoginRequest
	(*LoginResponse)(nil),             // 5: paulwwyvern.gophkeeper_proto.LoginResponse
	(*PushChangesRequest)(nil),        // 6: paulwwyvern.gophkeeper_proto.PushChangesRequest
	(*PullChangesRequest)(nil),        // 7: paulwwyvern.gophkeeper_proto.PullChangesRequest
	(*PullChangesResponse)(nil),       // 8: paulwwyvern.gophkeeper_proto.PullChangesResponse
	(*UploadFileChunk)(nil),           // 9: paulwwyvern.gophkeeper_proto.UploadFileChunk
	(*UploadFileResponse)(nil),        // 10: paulwwyvern.gophkeeper_proto.UploadFileResponse
	(*UploadFileQueryRequest)(nil),    // 11: paulwwyvern.gophkeeper_proto.UploadFileQueryRequest
	(*UploadFileQueryResponse)(nil),   // 12: paulwwyvern.gophkeeper_proto.UploadFileQueryResponse
	(*UploadFileStatusRequest)(nil),   // 13: paulwwyvern.gophkeeper_proto.UploadFileStatusRequest
	(*UploadFileStatusResponse)(nil),  // 14: paulwwyvern.gophkeeper_proto.UploadFileStatusResponse
	(*DownloadFileRequest)(nil),       // 15: paulwwyvern.gophkeeper_proto.DownloadFileRequest
	(*DownloadFileChunk)(nil),         // 16: paulwwyvern.gophkeeper_proto.DownloadFileChunk
	(*DownloadFileQueryRequest)(nil),  // 17: paulwwyvern.gophkeeper_proto.DownloadFileQueryRequest
	(*DownloadFileQueryResponse)(nil), // 18: paulwwyvern.gophkeeper_proto.DownloadFileQueryResponse
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 20: google.protobuf.Empty
}
var file_gophkeeper_proto_depIdxs = []int32{
	19, // 0: paulwwyvern.gophkeeper_proto.VaultItem.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: paulwwyvern.gophkeeper_proto.VaultItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: paulwwyvern.gophkeeper_proto.CreateUserRequest.user:type_name -> paulwwyvern.gophkeeper_proto.User
	0,  // 3: paulwwyvern.gophkeeper_proto.LoginResponse.user:type_name -> paulwwyvern.gophkeeper_proto.User
	1,  // 4: paulwwyvern.gophkeeper_proto.PushChangesRequest.items:type_name -> paulwwyvern.gophkeeper_proto.VaultItem
	19, // 5: paulwwyvern.gophkeeper_proto.PullChangesRequest.last_sync_time:type_name -> google.protobuf.Timestamp
	1,  // 6: paulwwyvern.gophkeeper_proto.PullChangesResponse.items:type_name -> paulwwyvern.gophkeeper_proto.VaultItem
	19, // 7: paulwwyvern.gophkeeper_proto.PullChangesResponse.sync_time:type_name -> google.protobuf.Timestamp
	2,  // 8: paulwwyvern.gophkeeper_proto.GophkeeperService.CreateUser:input_type -> paulwwyvern.gophkeeper_proto.CreateUserRequest
	4,  // 9: paulwwyvern.gophkeeper_proto.GophkeeperService.Login:input_type -> paulwwyvern.gophkeeper_proto.LoginRequest
	20, // 10: paulwwyvern.gophkeeper_proto.GophkeeperService.GetUser:input_type -> google.protobuf.Empty
	6,  // 11: paulwwyvern.gophkeeper_proto.GophkeeperService.PushChanges:input_type -> paulwwyvern.gophkeeper_proto.PushChangesRequest
	7,  // 12: paulwwyvern.gophkeeper_proto.GophkeeperService.PullChanges:input_type -> paulwwyvern.gophkeeper_proto.PullChangesRequest
	11, // 13: paulwwyvern.gophkeeper_proto.GophkeeperService.UploadFileQuery:input_type -> paulwwyvern.gophkeeper_proto.UploadFileQueryRequest
	13, // 14: paulwwyvern.gophkeeper_proto.GophkeeperService.UploadFileStatus:input_type -> paulwwyvern.gophkeeper_proto.UploadFileStatusRequest
	9,  // 15: paulwwyvern.gophkeeper_proto.GophkeeperService.UploadFile:input_type -> paulwwyvern.gophkeeper_proto.UploadFileChunk
	17, // 16: paulwwyvern.gophkeeper_proto.GophkeeperService.DownloadFileQuery:input_type -> paulwwyvern.gophkeeper_proto.DownloadFileQueryRequest
	15, // 17: paulwwyvern.gophkeeper_proto.GophkeeperService.DownloadFile:input_type -> paulwwyvern.gophkeeper_proto.DownloadFileRequest
	3,  // 18: paulwwyvern.gophkeeper_proto.GophkeeperService.CreateUser:output_type -> paulwwyvern.gophkeeper_proto.CreateUserResponse
	5,  // 19: paulwwyvern.gophkeeper_proto.GophkeeperService.Login:output_type -> paulwwyvern.gophkeeper_proto.LoginResponse
	0,  // 20: paulwwyvern.gophkeeper_proto.GophkeeperService.GetUser:output_type -> paulwwyvern.gophkeeper_proto.User
	20, // 21: paulwwyvern.gophkeeper_proto.GophkeeperService.PushChanges:output_type -> google.protobuf.Empty
	8,  // 22: paulwwyvern.gophkeeper_proto.GophkeeperService.PullChanges:output_type -> paulwwyvern.gophkeeper_proto.PullChangesResponse
	12, // 23: paulwwyvern.gophkeeper_proto.GophkeeperService.UploadFileQuery:output_type -> paulwwyvern.gophkeeper_proto.UploadFileQueryResponse
	14, // 24: paulwwyvern.gophkeeper_proto.GophkeeperService.UploadFileStatus:output_type -> paulwwyvern.gophkeeper_proto.UploadFileStatusResponse
	10, // 25: paulwwyvern.gophkeeper_proto.GophkeeperService.UploadFile:output_type -> paulwwyvern.gophkeeper_proto.UploadFileResponse
	18, // 26: paulwwyvern.gophkeeper_proto.GophkeeperService.DownloadFileQuery:output_type -> paulwwyvern.gophkeeper_proto.DownloadFileQueryResponse
	16, // 27: paulwwyvern.gophkeeper_proto.GophkeeperService.DownloadFile:output_type -> paulwwyvern.gophkeeper_proto.DownloadFileChunk
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
